# Shell variables
# Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/wallhaven-e7xw6w.png"

# Special
background='#001C2D'
foreground='#c99d8a'
cursor='#c99d8a'

# Colors
color0='#001C2D'
color1='#662A40'
color2='#863C32'
color3='#905017'
color4='#AA5A12'
color5='#BB610E'
color6='#96442C'
color7='#c99d8a'
color8='#8c6d60'
color9='#662A40'
color10='#863C32'
color11='#905017'
color12='#AA5A12'
color13='#BB610E'
color14='#96442C'
color15='#c99d8a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
