--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/wallhaven-e7xw6w.png"

-- Special
background="#001C2D"
foreground="#c99d8a"
cursor="#c99d8a"

-- Colors
color0="#001C2D"
color1="#662A40"
color2="#863C32"
color3="#905017"
color4="#AA5A12"
color5="#BB610E"
color6="#96442C"
color7="#c99d8a"
color8="#8c6d60"
color9="#662A40"
color10="#863C32"
color11="#905017"
color12="#AA5A12"
color13="#BB610E"
color14="#96442C"
color15="#c99d8a"
