# Shell variables
# Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/1632615567617.jpg"

# Special
background='#121212'
foreground='#e0d0dc'
cursor='#e0d0dc'

# Colors
color0='#121212'
color1='#767086'
color2='#9F6C8F'
color3='#C6739B'
color4='#7E848A'
color5='#A594A9'
color6='#C4A4BB'
color7='#e0d0dc'
color8='#9c919a'
color9='#767086'
color10='#9F6C8F'
color11='#C6739B'
color12='#7E848A'
color13='#A594A9'
color14='#C4A4BB'
color15='#e0d0dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
