--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/1632615567617.jpg"

-- Special
background="#121212"
foreground="#e0d0dc"
cursor="#e0d0dc"

-- Colors
color0="#121212"
color1="#767086"
color2="#9F6C8F"
color3="#C6739B"
color4="#7E848A"
color5="#A594A9"
color6="#C4A4BB"
color7="#e0d0dc"
color8="#9c919a"
color9="#767086"
color10="#9F6C8F"
color11="#C6739B"
color12="#7E848A"
color13="#A594A9"
color14="#C4A4BB"
color15="#e0d0dc"
