--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/hdd/ironman/wallpapers/8a5c88a3c6ccf69177593c0fe9a20a951df99b3fcb7e68260bfc4d6a948c75793d2e.png"

-- Special
background="#0e1011"
foreground="#c7c8c8"
cursor="#c7c8c8"

-- Colors
color0="#0e1011"
color1="#5C5E5F"
color2="#AB1C1D"
color3="#19678C"
color4="#19688D"
color5="#7D7F80"
color6="#7F8081"
color7="#c7c8c8"
color8="#8b8c8c"
color9="#5C5E5F"
color10="#AB1C1D"
color11="#19678C"
color12="#19688D"
color13="#7D7F80"
color14="#7F8081"
color15="#c7c8c8"
