#! /bin/sh

sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width		2
bspc config window_gap			0
bspc config bottom_padding      20

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set the border colors.
# new colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# changing border size script
#~/scripts/borderBspwm &


# desktop rules
#bspc rule -a qutebrowser desktop='^1'
bspc rule -a qutebrowser desktop=^1 follow=off
bspc rule -a Chromium desktop='^1'
#bspc rule -a obsidian desktop='^3' center=true state=floating rectangle=1500x900+0+0
bspc rule -a obsidian desktop='^3' follow=off
bspc rule -a discord desktop='^9' follow=off
bspc rule -a "java-lang-Thread"  desktop='^2' state=floating
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a jetbrains-webstorm desktop='^2'
bspc rule -a  "jetbrains-pycharm-ce" desktop='^2'
bspc rule -a Thunar state=floating center=true rectangle=1200x650+0+0
bspc rule -a vlc state=floating rectangle=1000x600+500+300  layer=above 
bspc rule -a Genymotion state=floating
bspc rule -a "Android Emulator" state=floating
bspc rule -a "Genymotion Player" desktop='^3' state=floating
bspc rule -a Unity desktop='^4' state=floating
bspc rule -a Pavucontrol state=floating rectangle=1000x600+500+300
bspc rule -a Leafpad state=floating
#bspc rule -a Sxiv state=floating rectangle=1000x1000+0+0
bspc rule -a Sxiv state=floating center=true rectangle=800x800+0+0
#bspc rule -a Zathura state=floating rectangle=1000x1000+0+0
bspc rule -a Zathura state=tiled

# Startup programs
# transparency
#picom &	
# set wallpaper
wal -i $(cat ~/.cache/wal/wal) -o ~/scripts/setWal.sh &
# status bar
~/.config/polybar/launch.sh &
# keyboard mouse speed
#xset r rate 500 40
# set curser  style to pointer
exec xsetroot -cursor_name left_ptr &                                                                       
# kde Connect
/usr/lib/kdeconnectd &
# thuner daemon
thunar --daemon &
# track all my activies in this machine
#rescuetime &
# notification
dunst &
# start local server
~/scripts/startServer.sh &
# start syning file with mobile
syncthing &
# Activity watcher
#$HOME/scripts/activityWatcherStartup &
# backup files to google drive
$HOME/scripts/backup &
# sync youtube playlist
$HOME/scripts/syncYoutubePlaylist &
# ibus
ibus-daemon -drxR &
# mpd kde support
$HOME/scripts/mpdStartup &
## Screen off time
## https://wiki.archlinux.org/title/Display_Power_Management_Signaling
xset -dpms &
xset s off &
# keyboard chattering
#xset r rate 1200 70 


