#!/usr/bin/env python3

import logging
import os
import plistlib
import requests
import sys
import webbrowser


CONSUMER_KEY = "99580-d8c9334c37cb043b2d13de49"
BASE_URL = "https://getpocket.com"
REDIRECT_URL = "localhost"

logger = logging.getLogger(__name__)
urls = []


def extract_urls(node):
    children = node.get("Children", [])
    url = node.get("URLString")
    if url:
        urls.append(url)
    for child in children:
        extract_urls(child)


def read_plist():
    filename = os.path.expanduser("~/Library/Safari/Bookmarks.plist")
    with open(filename, 'rb') as handler:
        plist = plistlib.load(handler)
        extract_urls(plist)


def post(url, data):
    headers = {
        "x-accept": "application/json",
    }
    response = requests.post(url, data=data, headers=headers)
    error = response.headers.get("X-Error")
    if error:
        logger.error(f"{response.status_code}, {error}")
        response.raise_for_status()
    else:
        return response.json()


def request_code():
    payload = {
        "consumer_key": CONSUMER_KEY,
        "redirect_uri": REDIRECT_URL,
    }
    response = post(f"{BASE_URL}/v3/oauth/request", payload)
    return response["code"]


def request_access_token(code):
    payload = {
        "consumer_key": CONSUMER_KEY,
        "code": code,
    }
    response = post(f"{BASE_URL}/v3/oauth/authorize", payload)
    return response["access_token"]


def request_authorization(code):
    url = f"{BASE_URL}/auth/authorize?request_token={code}&redirect_uri={REDIRECT_URL}"
    webbrowser.open(url, new=2)


def authenticate_pocket():
    code = request_code()
    request_authorization(code)
    input("Press any key after authorizing app...")
    return request_access_token(code)


def add_item(url, token):
    payload = {
        "url": url,
        "consumer_key": CONSUMER_KEY,
        "access_token": token,
    }
    return post("https://getpocket.com/v3/add", payload)

def pocket_list(token):
    payload = {
        "consumer_key": CONSUMER_KEY,
        "access_token": token,
    }
    return post("https://getpocket.com/v3/get", payload)




def main():
    # read_plist()
    # if you want to login again run this for access_token value
    # access_token = authenticate_pocket()
    # logger.info("Successfully authenticated with Pocket")
    # print(access_token)
    
    # after login
    access_token = "fdc2aeea-158b-52eb-59af-ba0d87"
    listofurl= pocket_list(access_token)

    for i in listofurl["list"]:
        print(listofurl["list"][i]["given_url"])
        
    # f = open("pocket_list.json", "a")
    # f.write(str(listofurl))
    # f.close()
    # print("check python_list.json")
 


if __name__ == '__main__':
    sys.exit(main())
