#!/bin/bash

videoUrl="https://www.youtube.com/playlist?list=PLv2yDojCCtNYZY8uirmJpzrpnmT3j7UMA"
audioUrl="https://www.youtube.com/playlist?list=PLv2yDojCCtNYer5lHMj5sI4MchJ6u7yHa"

# download audio
cd $audioDownloadDir
youtube-dl  --download-archive .downloaded.txt --cookies .cookies.txt --metadata-from-title "%(artist)s - %(title)s - %(uploader)s" --add-metadata  --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3 $audioUrl

# download video
cd $videoDownloadDir 
youtube-dl  --download-archive .downloaded.txt --cookies .cookies.txt --sub-lang en --convert-subs srt --write-sub --output "%(title)s.%(ext)s" -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' --merge-output-format mp4 $videoUrl
